apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: arcaks-secret-provider
  namespace: apis
spec:
  provider: azure
  secretObjects:
  - secretName: sqlconnsecret
    type: Opaque    
    data:
    - objectName: "AzureWebJobsStorage"
      key: "AzureWebJobsStorage"
    - objectName: "SQLConnectionString"
      key: "SQLConnectionString"
    - objectName: "LOGICAPP-CALLBACK-URL"
      key: "LOGICAPP_CALLBACK_URL"
    - objectName: "LOGICAPP-POST-URL"
      key: "LOGICAPP_POST_URL"
  - secretName: sqlarcmilasecret
    type: Opaque
    data:
    - objectName: "AzureWebJobsStorage"
      key: "AzureWebJobsStorage"
    - objectName: "WORKFLOWAPP-AAD-CLIENTID"
      key: "WORKFLOWAPP_AAD_CLIENTID"
    - objectName: "WORKFLOWAPP-AAD-CLIENTSECRET"
      key: "WORKFLOWAPP_AAD_CLIENTSECRET"
    - objectName: "WORKFLOWAPP-AAD-OBJECTID"
      key: "WORKFLOWAPP_AAD_OBJECTID"
    - objectName: "WORKFLOWAPP-AAD-TENANTID"
      key: "WORKFLOWAPP_AAD_TENANTID"    
    - objectName: "outlook-connectionKey"
      key: "outlook-connectionKey"    
  parameters:
    usePodIdentity: "false"
    keyvaultName: arcakskv
    objects:  |
      array:
        - |
          objectName: "AzureWebJobsStorage"
          objectType: secret
        - |
          objectName: "SQLConnectionString"
          objectType: secret
        - |
          objectName: "WORKFLOWAPP-AAD-CLIENTID"
          objectType: secret
        - |
          objectName: "WORKFLOWAPP-AAD-CLIENTSECRET"
          objectType: secret
        - |
          objectName: "WORKFLOWAPP-AAD-OBJECTID"
          objectType: secret
        - |
          objectName: "WORKFLOWAPP-AAD-TENANTID"
          objectType: secret
        - |
          objectName: "LOGICAPP-CALLBACK-URL"
          objectType: secret
        - |
          objectName: "LOGICAPP-POST-URL"
          objectType: secret
        - |
          objectName: "outlook-connectionKey"
          objectType: secret
    tenantId: ""